# Generated by Django 4.1.7 on 2023-05-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0002_alter_projekt_proj_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(help_text='Nazwa pomieszczenia', max_length=50)),
                ('r_number', models.CharField(help_text='Numer pomieszczenia', max_length=10)),
                ('r_area', models.DecimalField(decimal_places=2, help_text='Powierzchnia w m2', max_digits=5)),
                ('r_people', models.PositiveIntegerField(help_text='Ilość osób w pomieszczeniu')),
                ('projekt', models.ForeignKey(help_text='Projekt, w którym jest pomieszczenie', on_delete=django.db.models.deletion.CASCADE, to='zyski.projekt')),
            ],
        ),
    ]
