# Generated by Django 4.1.7 on 2023-05-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0005_rooms_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='r_comment',
            field=models.CharField(blank=True, help_text='Komentarz do pomieszczenia', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='r_devices',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Emisja od urządzeń W', null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='r_group',
            field=models.CharField(blank=True, help_text='Grupa pomieszczenia', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='r_light',
            field=models.PositiveIntegerField(default=20, help_text='Emisja od oświetlenia W/m2'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='r_temp',
            field=models.PositiveIntegerField(default=20, help_text='Temperatura w pomieszczeniu'),
        ),
    ]
