# Generated by Django 4.1.7 on 2023-05-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0006_rooms_r_comment_rooms_r_devices_rooms_r_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='r_person',
            field=models.PositiveIntegerField(default=80, help_text='Emisja ciepła od ludzi W/os'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='r_comment',
            field=models.CharField(blank=True, default='', help_text='Komentarz do pomieszczenia', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='r_group',
            field=models.CharField(blank=True, default='', help_text='Grupa pomieszczenia', max_length=10, null=True),
        ),
    ]
