# Generated by Django 4.1.7 on 2023-05-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0007_rooms_r_person_alter_rooms_r_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='r_comment',
            field=models.CharField(blank=True, default='', help_text='Komentarz do pomieszczenia', max_length=80),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='r_group',
            field=models.CharField(blank=True, default='', help_text='Grupa pomieszczenia', max_length=10),
        ),
    ]
