# Generated by Django 4.1.7 on 2023-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0008_alter_rooms_r_comment_alter_rooms_r_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='r_area',
            field=models.PositiveIntegerField(help_text='Powierzchnia w m2'),
        ),
    ]
