# Generated by Django 4.1.7 on 2023-05-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0010_rooms_results_res_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='r_air',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Powietrze infiltracyjne'),
        ),
    ]
