# Generated by Django 4.1.7 on 2023-05-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0011_rooms_r_air'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kierunek', models.CharField(blank=True, choices=[('N', 'n'), ('NW', 'nw'), ('W', 'w'), ('SW', 'sw'), ('S', 's'), ('SE', 'se'), ('E', 'e'), ('NE', 'ne')], max_length=5, null=True, verbose_name='Kierunek świata przegrody')),
                ('klasa', models.CharField(blank=True, choices=[('KLASA_1', 'Klasa_1'), ('KLASA_2', 'Klasa_2'), ('KLASA_3', 'Klasa_3'), ('KLASA_4', 'Klasa_4'), ('KLASA_5', 'Klasa_5'), ('KLASA_6', 'Klasa_6')], default='KLASA_3', max_length=10, null=True, verbose_name='Klasa przegrody')),
                ('wall_U', models.PositiveIntegerField(help_text='Współczynnik przenikania ciepła ściany W/m2')),
            ],
        ),
        migrations.CreateModel(
            name='WallsRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_area', models.PositiveIntegerField(help_text='Powierzchnia ściany w m2')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zyski.rooms')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zyski.walls')),
            ],
        ),
        migrations.AddField(
            model_name='walls',
            name='pom',
            field=models.ManyToManyField(through='zyski.WallsRooms', to='zyski.rooms'),
        ),
        migrations.AddField(
            model_name='walls',
            name='projekt',
            field=models.ForeignKey(help_text='Projekt, w którym jest ściana', on_delete=django.db.models.deletion.CASCADE, to='zyski.projekt'),
        ),
    ]
