# Generated by Django 4.1.7 on 2023-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0012_walls_wallsrooms_walls_pom_walls_projekt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walls',
            name='pom',
        ),
        migrations.AddField(
            model_name='rooms',
            name='walls',
            field=models.ManyToManyField(through='zyski.WallsRooms', to='zyski.walls'),
        ),
    ]
