# Generated by Django 4.1.7 on 2023-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0013_remove_walls_pom_rooms_walls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walls',
            name='kierunek',
        ),
        migrations.AddField(
            model_name='walls',
            name='wall_description',
            field=models.CharField(blank=True, help_text='Opis ściany', max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='walls',
            name='wall_name',
            field=models.CharField(blank=True, help_text='Nazwa ściany', max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='walls',
            name='wall_symbol',
            field=models.CharField(default='SZ1', help_text='Symbol ściany', max_length=10),
        ),
        migrations.AddField(
            model_name='wallsrooms',
            name='kierunek',
            field=models.CharField(blank=True, choices=[('N', 'n'), ('NW', 'nw'), ('W', 'w'), ('SW', 'sw'), ('S', 's'), ('SE', 'se'), ('E', 'e'), ('NE', 'ne')], max_length=5, null=True, verbose_name='Kierunek świata przegrody'),
        ),
    ]
