# Generated by Django 4.1.7 on 2023-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0014_remove_walls_kierunek_walls_wall_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walls',
            name='klasa',
            field=models.CharField(blank=True, choices=[('KLASA_1', 'Klasa 1'), ('KLASA_2', 'Klasa 2'), ('KLASA_3', 'Klasa 3'), ('KLASA_4', 'Klasa 4'), ('KLASA_5', 'Klasa 5'), ('KLASA_6', 'Klasa 6')], default='KLASA_3', max_length=10, null=True, verbose_name='Klasa przegrody'),
        ),
        migrations.AlterField(
            model_name='wallsrooms',
            name='kierunek',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('NW', 'Nw'), ('W', 'W'), ('SW', 'Sw'), ('S', 'S'), ('SE', 'Se'), ('E', 'E'), ('NE', 'Ne')], max_length=5, null=True, verbose_name='Kierunek świata przegrody'),
        ),
    ]
