# Generated by Django 4.1.7 on 2023-05-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyski', '0015_alter_walls_klasa_alter_wallsrooms_kierunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walls',
            name='klasa',
            field=models.CharField(choices=[('KLASA_1', 'Klasa 1'), ('KLASA_2', 'Klasa 2'), ('KLASA_3', 'Klasa 3'), ('KLASA_4', 'Klasa 4'), ('KLASA_5', 'Klasa 5'), ('KLASA_6', 'Klasa 6')], default='KLASA_3', max_length=10, verbose_name='Klasa przegrody'),
        ),
        migrations.AlterField(
            model_name='walls',
            name='wall_U',
            field=models.FloatField(help_text='Współczynnik przenikania ciepła ściany W/m2', max_length=15),
        ),
    ]
